version: "2"
services:
  php:
    env_file: .env
    build:
      context: ./php
      args:
        - "EMONCMS_WEB_DIR=${WEB_DIR}/${APPNAME}"
        - "PHPFINA_DIR=${PHPFINA_DIR}"
        - "PHPTIMESERIES_DIR=${PHPTIMESERIES_DIR}"
        - "EMONCMS_DATA_DIR=${EMONCMS_DATA_DIR}"
        - "LOG_LOCATION=${LOG_LOCATION}"
        - "PHP_VERSION=${PHP_VERSION}"
        - "EMONCMS_DIR=${EMONCMS_DIR}"
        - "EMONHUB_DIR=${EMONHUB_DIR}"
        - "EMONHUB_LOG=${EMONHUB_LOG}"
    volumes:
      - "www:${WEB_DIR}"
      - "phpfina:${PHPFINA_DIR}"
      - "phptimeseries:${PHPTIMESERIES_DIR}"
      - "emoncms-log:${LOG_LOCATION}"
      - "emoncms-dir:${EMONCMS_DIR}"
      - "emonhub-dir:${EMONHUB_DIR}"
      - "emonhub-log:${EMONHUB_LOG}"
      - "var-lock:/var/lock"
    environment:
      - "EMONCMS_WEB_DIR=${WEB_DIR}/${APPNAME}"

    working_dir: ${WEB_DIR}/${APPNAME}
    restart: always

  apache:
    build: ./apache
    depends_on: ["php", "db", "redis"]
    volumes: ["www:${WEB_DIR}"]
    ports: ["${WEB_PORT}:80"]
    restart: always

  db:
    build:
        context: ./mysql
        args:
          - "MYSQL_DOCKER_IMAGE=${MYSQL_DOCKER_IMAGE}"
    volumes: ["db:${MYSQL_DATA_DIR}"]
    env_file: .env
    restart: always

  redis:
    image: redis:5
    volumes: ["redis:${REDIS_DATA_DIR}"]
    env_file: .env
    restart: always

  mqtt:
    image: eclipse-mosquitto:1.6
    env_file: .env
    restart: always

  emoncms_mqtt:
    build: ./emoncms_mqtt/
    depends_on: ["php"]
    command: sh -c "sleep 5; SCRIPT_FILENAME=${WEB_DIR}/${APPNAME}/scripts/services/emoncms_mqtt/emoncms_mqtt.php REQUEST_METHOD=GET cgi-fcgi -bind -connect php:9000"
    restart: always

  emoncms_feedwriter:
    build: ./emoncms_feedwriter
    depends_on: ["php"]
    command: sh -c "sleep 5; SCRIPT_FILENAME=${WEB_DIR}/${APPNAME}/scripts/feedwriter.php REQUEST_METHOD=GET cgi-fcgi -bind -connect php:9000"
    restart: always

  emoncms_service-runner:
    build: ./emoncms_service-runner
    depends_on: ["redis","php"]
    volumes: ["www:${WEB_DIR}","emoncms-dir:${EMONCMS_DIR}"]
    command: sh -c "sleep 5; python ${WEB_DIR}/${APPNAME}/scripts/services/service-runner/service-runner.py"
    env_file: .env
    restart: always

  emonhub:
    build:
      context: ./emonhub
      args:
        - "EMONCMS_WEB_DIR=${WEB_DIR}/${APPNAME}"
        - "EMONHUB_DIR=${EMONHUB_DIR}"
        - "EMONHUB_CONF=${EMONHUB_CONF}"
    depends_on: ["mqtt"]
    privileged: true
    restart: always
    volumes:
       - "www:${WEB_DIR}"
       - "emoncms-dir:${EMONCMS_DIR}"
       - "emonhub-dir:${EMONHUB_DIR}"
       - "emoncms-log:${LOG_LOCATION}"
    env_file: .env
    environment:
      - "EMONCMS_WEB_DIR=${WEB_DIR}/${APPNAME}"
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    command: sh -c "sleep 5; python3 ${EMONHUB_DIR}/src/emonhub.py --config-file=${EMONHUB_CONF}"

volumes:
  db:
  www:
  redis:
  phpfina:
  phptimeseries:
  emoncms-log:
  emoncms-dir:
  emonhub-dir:
  emonhub-log:
  var-lock:
 

